---

- name: Download duplicacy
  get_url:
    url: "{{ duplicacy_url }}"
    dest: /usr/local/bin/duplicacy
    mode: u=rwx,g=rx,o=rx
  become: yes

- name: Set dropbox token
  lineinfile:
    path: /etc/environment
    regexp: "^DUPLICACY_DROPBOX_TOKEN="
    line: "DUPLICACY_DROPBOX_TOKEN={{ dropbox_token }}"
    state: present
  become: yes

- name: Create backup folder
  file:
    path: "{{ backup_folder }}"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_user }}"
    state: directory
    mode: "ug=rwx,o-rwx"
  become: true

- name: Initialise backups
  command: "duplicacy -background init confluence {{ dropbox_folder }}"
  args:
    chdir: "{{ backup_folder }}"
  register: init_cmd
  failed_when: "'Error' in init_cmd.stderr"

- name: Create scripts folder
  file:
    path: "{{ backup_folder }}/.duplicacy/scripts"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_user }}"
    state: directory
    mode: "ug=rwx,o-rwx"
  become: true

- name: Make backup script
  template:
    src: pre-backup.sh.j2
    dest: "{{ backup_folder }}/.duplicacy/scripts/pre-backup"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_user }}"
    mode: "0755"
  become: true

- name: Backup cron job
  cron:
    name: "Backup confluence"
    value: "cd {{ backup_folder }} && /usr/local/bin/duplicacy backup"
    minute: "0"
    hour: "4"
    state: present
  become: true
