---

- name: Stop confluence
  systemd:
    name: confluence
    state: stopped
  become: true

- name: Update symlink version to install
  file:
    src: "{{ confluence_dirs.versions }}/atlassian-confluence-{{ confluence_version }}"
    dest: "{{ confluence_running_dir }}"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_user }}"
    state: link
  become: yes

- name: Update confluence config
  lineinfile:
    path: "{{ confluence_running_dir }}/confluence/WEB-INF/classes/confluence-init.properties"
    regexp: "^# confluence.home=c:/confluence/data"
    line: "confluence.home={{ confluence_dirs.data }}"
    backrefs: yes
    owner: "{{ confluence_user }}"
    group: "{{ confluence_user }}"
  become: yes

- name: Enable and start confluence service
  systemd:
    name: confluence
    state: started
    enabled: yes
    daemon_reload: yes
  become: true
