---

- name: Add webupd8team/java repo
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
  become: yes

- name: Java automation dependencies
  apt:
    name: software-properties-common
    update_cache: yes
    cache_valid_time: 3600
    state: present
  become: yes

- name: Accept oracle license
  debconf:
    name: "oracle-java{{ java_version }}-installer"
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select
  become: yes

- name: Seen oracle license
  debconf:
    name: "oracle-java{{ java_version }}-installer"
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: seen
  become: yes

- name: Install java
  apt:
    name: "oracle-java{{ java_version }}-installer"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  become: yes
