---

- name: Add postgres apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Add postgres repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg
  become: yes

- name: Install postgres
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: yes
  become: yes
