---

- name: Add postgres apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Add postgres repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg
  become: yes

- name: Install postgres
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: yes
  become: yes

- name: Install psycopg2
  apt:
    name: "python-psycopg2"
    state: present
    update_cache: yes
  become: yes

- name: Create db
  postgresql_db:
    name: "{{ postgres_db_name }}"
    encoding: UTF8
    template: template0
  become: yes
  become_user: postgres

- name: Create db user
  postgresql_user:
    db: "{{ postgres_db_name }}"
    name: "{{ postgres_db_user }}"
    priv: ALL
    state: present
  become: yes
  become_user: postgres
